import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ScentForge Atelier",
  description: "Affiliate perfume commerce generated by Codex and validated before publish.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full">{children}</body>
    </html>
  );
}
